#Project Euler Question 2
#Rachel Nash
#Even Fibonacci Numbers
#Answer: 4613732
"""Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values
do not exceed four million, find the sum of the even-valued terms."""
first=1
second=1
evens = []
while first+second<=4000000:
    next = first+second
    if next%2.0 ==0:
        evens.append(next)
    first=second
    second=next
print sum(evens)